name: morvenn
title: Homework page 
description: An example of technical documentation hosted on Github pages, using the Just the Docs Jekyll theme
remote_theme: morvenn/just-the-docs

color_scheme: dark

# logo: "/assets/images/Morris_badge.png"

aux_links:
  "Source repository on GitHub":
    - "//github.com/morvenn/Techcom"

back_to_top: true
back_to_top_text: "Back to top"

footer_content: "&copy; 2021 Magda Niedźwiecka"